feature/op 20
nicotine189/OpenAssoSport pull request #3
Opened 2024-11-22 16:31 UTC by nicotine189

Adding the header component with basic elements and a logo of a club
Adding directories to structure the files
Switch en to fr in the html file

2024-11-24 13:02 UTC, Tiki102 commented on front/src/app/core/components/header/header.component.html
> +    <img src="images/Logo_NCR.svg" alt="Logo" class="logo-img" />
Améliorer l'attribut alt du logo et remplacé la fin de la ligne par :

 alt="Logo du Club NCR">

2024-11-24 14:07 UTC, Tiki102 requested changes
Top ! Merci pour le logo :+1:

2024-11-24 14:07 UTC, Tiki102 commented on front/src/app/core/components/header/header.component.ts
> +  styleUrl: './header.component.scss'
Correction du fichier header.component.ts dans la déclaration des styles : 
 
 Le fichier header.component.ts présente une erreur dans la déclaration des styles du composant. L'attribut utilisé était styleUrl (au singulier), alors qu'Angular exige l'attribut styleUrls (au pluriel). Cette erreur empêche le chargement des styles et cause un dysfonctionnement visuel du composant.
 
 Remplace `styleUrl` par `styleUrls`

2024-11-24 14:07 UTC, Tiki102 commented on front/src/app/core/components/header/header.component.spec.ts
Ajouter explicitement MatIconModule dans les imports du fichier de test pour que les dépendances du composant soient disponibles.

Voici le fichier corrigé :

```
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { MatIconModule } from '@angular/material/icon'; // Ajout du module nécessaire
import { HeaderComponent } from './header.component';

describe('HeaderComponent', () => {
  let component: HeaderComponent;
  let fixture: ComponentFixture<HeaderComponent>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [HeaderComponent, MatIconModule] // Ajout de MatIconModule ici
    })
    .compileComponents();

    fixture = TestBed.createComponent(HeaderComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
```

2024-11-24 14:07 UTC, Tiki102 commented on front/public/images/Logo_NCR.jpg
Top ! Merci pour le logo 👍

2024-11-24 14:20 UTC, Tiki102 requested changes
Je découvre les reviews alors je ne sais pas si je fais les bonnes manips. En tout cas j'ai essayé de te laisser des commentaires les plus explicatifs possibles. (parfois même un peu trop, tu me diras ce que t'en penses, j'ajusterais avec le temps). J'ai pas pull ni tester, je me suis aider de Chatou. Donc si tu vois que ce que je t'ai écris c'est pas bon, zappe les. Pour la RGAA par contre il plutôt bon dans le domaine.

2024-11-29 13:29 UTC, nicotine189 commented on front/src/app/core/components/header/header.component.html
> +    <img src="images/Logo_NCR.svg" alt="Logo" class="logo-img" />
done

2024-11-29 13:39 UTC, nicotine189 commented on front/src/app/core/components/header/header.component.scss
> +
Ajout ok, pour le moment je ne vois pas de résultat : à tester par la suite

2024-11-29 13:47 UTC, nicotine189 commented on front/src/app/core/components/header/header.component.ts
> +  styleUrl: './header.component.scss'
A revoir : lorsque j'ajoute le 's', l'IDE ne comprends pas

2024-11-29 13:59 UTC, merged